// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = const FirebaseOptions(
    apiKey: 'AIzaSyDlVCNfCjpJ70L01ZxF2dLgWCpksNMJotg',
    appId: '1:1032783101082:web:6e13ab74e1727d55d9f323',
    messagingSenderId: '1032783101082',
    projectId: 'symb-att-mgmt',
    authDomain: 'symb-att-mgmt.firebaseapp.com',
    storageBucket: 'symb-att-mgmt.appspot.com',
    measurementId: 'G-TKT0NC58QW',
  );

  static FirebaseOptions android = const FirebaseOptions(
    apiKey: 'AIzaSyB8UjuXeQSgaQdGYxXWVqqO_eyKVbml1mo',
    appId: '1:1032783101082:android:d9537f4cf5b02511d9f323',
    messagingSenderId: '1032783101082',
    projectId: 'symb-att-mgmt',
    storageBucket: 'symb-att-mgmt.appspot.com',
  );

  static FirebaseOptions ios = const FirebaseOptions(
    apiKey: 'AIzaSyCKcDsNUBf6VXeeChgqgVOEIkHU3DQ_XD4',
    appId: '1:1032783101082:ios:203a659ce29f1915d9f323',
    messagingSenderId: '1032783101082',
    projectId: 'symb-att-mgmt',
    storageBucket: 'symb-att-mgmt.appspot.com',
    iosClientId:
        '1032783101082-4nk346jehqkfttcfemcehftcmmcklhf0.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendenceManagementSystem',
  );
}
